#!/bin/bash

set -e

KEY_STORE_PATH="$PWD/cassandra-config/conf/certs"
mkdir -p "$KEY_STORE_PATH"
KEY_STORE="$KEY_STORE_PATH/cassandra.keystore"
PKS_KEY_STORE="$KEY_STORE_PATH/cassandra.pks12.keystore"
TRUST_STORE="$KEY_STORE_PATH/cassandra.truststore"
PASSWORD=$1
CLUSTER_NAME=$2
CLUSTER_PUBLIC_CERT="$KEY_STORE_PATH/CLUSTER_${CLUSTER_NAME}_PUBLIC.cer"

### Cluster key setup.
# Create the cluster key for cluster communication.
# Creates cassandra.keystore which contains private key for cluster
keytool -genkey -keyalg RSA -alias "${CLUSTER_NAME}_CLUSTER" -keystore "$KEY_STORE" -storepass "$PASSWORD" -keypass "$PASSWORD" \
-dname "CN=Acme Image $CLUSTER_NAME cluster, OU=Acme, O=Acme, L=Toronto, ST=ON, C=CA, DC=Acme, DC=com" \
-validity 36500

# Create the public key for the cluster which is used to identify nodes.
# Creates CLUSTER_{CLUSTER_NAME}_PUBLIC.cer
keytool -export -alias "${CLUSTER_NAME}_CLUSTER" -file "$CLUSTER_PUBLIC_CERT" -keystore "$KEY_STORE" \
-storepass "$PASSWORD" -keypass "$PASSWORD" -noprompt

# Import the identity of the cluster public cluster key into the trust store so that nodes can identify each other.
# Creates cassandra.truststore which contains the cluster public key
keytool -import -v -trustcacerts -alias "${CLUSTER_NAME}_CLUSTER" -file "$CLUSTER_PUBLIC_CERT" -keystore "$TRUST_STORE" \
-storepass "$PASSWORD" -keypass "$PASSWORD" -noprompt

# Creates a pkcs12 keystore from the cassandra.keystore
keytool -importkeystore -srckeystore "$KEY_STORE" -destkeystore "$PKS_KEY_STORE" -deststoretype PKCS12 \
-srcstorepass "$PASSWORD" -deststorepass "$PASSWORD"

# Exports pem file without private keys with the public certs for cluster and client
# Note: Client will only need to use the cluster public certificate when require_client_auth: false
openssl pkcs12 -in "$PKS_KEY_STORE" -nokeys -out "cluster-ca-certificate.pem" -passin "pass:$PASSWORD"

sed -e "s/keystore_password: cassandra/keystore_password: $PASSWORD/g" cassandra-config/cassandra.yaml.base > cassandra-config/cassandra.yaml
sed -i.bak -e "s/truststore_password: cassandra/truststore_password: $PASSWORD/g" cassandra-config/cassandra.yaml